# Generated by Django 5.2 on 2025-06-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
