# Generated by Django 5.2 on 2025-07-07 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_reservation_car_alter_spot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.car'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('disabled', 'Disabled')], default='available', max_length=10),
        ),
    ]
