# Generated by Django 5.2 on 2025-07-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_spot_is_disabled_alter_reservation_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='buzzer_active',
            field=models.BooleanField(default=True),
        ),
    ]
