# Generated by Django 5.2 on 2025-07-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_spot_buzzer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='parked',
            field=models.BooleanField(default=False),
        ),
    ]
